version: "3.8"

services:
  php-apache-environment:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hrm-php-apache
    ports:
      - 2007:80
    networks:
      - bridge

  hrm_db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Coderz12!@
      MYSQL_DATABASE: hrm_db
      MYSQL_USER: hrm-user
      MYSQL_PASSWORD: Coderz12!@
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "1103:3306"
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
